# Пароль для доступа
PASSWORD = "8989"

# Токены из .env
MS_TOKEN = "02b477550ca28ff34ba74cdad7596621c6b37e1e"
MP_API_KEY = "Yzc0YmNlNzg5YmI0YWI4ODYzMDhkNzZmYjJiODBiNmY1ZTM1ZGFmNw"
IP_API_URL = "http://msmp.pricing.su/api/ur_summary"
IP_API_USER = "admin"
IP_API_PASS = "n4bNgNJF"
GOOGLE_SHEET_ID = "19nnrPEb88DddCsAA3YtUpSMiHixMJocETB0mOnHycQI"
